backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "content/noticias"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Descrição", name: "description", widget: "text" }

  - name: "podcasts"
    label: "Podcasts"
    folder: "content/podcasts"
    create: true
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Áudio", name: "audio", widget: "file" }
      - { label: "Descrição", name: "description", widget: "text" }
